# Setup
title:        3AM Deep Time
subtitle:     게임 개발자를 꿈꾸는 시간
tagline:      Unity, C#, Game Math, Algorithm
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Doorwhichisclosed
  url:        https://github.com/doorwhichisclosed

# Gems
gems:
  - jekyll-paginate
  
#Plugins
plugins: [jekyll-paginate]

#Others
markdown: kramdown
asset_url: /assets