# Setup
title:        3AM Deep Time
tagline:      Unity, C#, Game Math, Algorithm
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Doorwhichisclosed
  url:        https://github.com/doorwhichisclosed

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown